# Generated by Django 5.2.6 on 2025-10-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LECTOR', 'Lector'), ('ADMIN', 'Administrador'), ('SUPERUSUARIO', 'Superusuario')], default='LECTOR', help_text='Rol del usuario: Lector (por defecto), Admin o Superusuario', max_length=20, verbose_name='Rol'),
        ),
    ]
