# Generated by Django 5.2.6 on 2025-10-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_comentariotema_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='imagen',
        ),
    ]
