# Generated by Django 5.2.6 on 2025-09-22 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='categoria_blog',
            field=models.ForeignKey(blank=True, help_text='Selecciona la categoría a la que pertenece este blog', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.categoria_blog', verbose_name='Categoría del blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='Imagen'),
        ),
    ]
