# Generated by Django 5.2.6 on 2025-09-23 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_banner_alter_blog_categoria_blog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioblog',
            name='nivel',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='comentarioblog',
            index=models.Index(fields=['blog', 'parent'], name='blog_coment_blog_id_b3eb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarioblog',
            index=models.Index(fields=['blog', 'nivel'], name='blog_coment_blog_id_b5b452_idx'),
        ),
    ]
