# Generated by Django 5.2.6 on 2025-10-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comentarioblog_nivel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='categoria_blog',
            field=models.ForeignKey(blank=True, help_text='Selecciona la categoría a la que pertenece este blog', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.categoria_blog', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo_blog',
            field=models.CharField(max_length=200, verbose_name='Título del noticia'),
        ),
        migrations.AlterField(
            model_name='categoria_blog',
            name='nombre_categoria',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre de la noticias'),
        ),
    ]
