# Generated by Django 5.2.7 on 2025-10-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_articulos_categoria_articulo'),
        ('blog', '0005_alter_blog_options_alter_blog_categoria_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categoria_blog',
        ),
        migrations.DeleteModel(
            name='Categoria_Blog',
        ),
    ]
