# Generated by Django 5.2.7 on 2025-10-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_banner_alter_blog_imagen_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
