# Generated by Django 5.2.6 on 2025-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=200, verbose_name='Nombre')),
                ('correo_electronico', models.EmailField(max_length=200, verbose_name='correo electrónico')),
                ('telefono_contacto', models.IntegerField(blank=True, verbose_name='Teléfono')),
                ('sitio_web_contacto', models.URLField(blank=True, verbose_name='Sitio web')),
                ('mensaje_contacto', models.TextField(blank=True, verbose_name='Mensaje')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de envío')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Ediciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edicion', models.PositiveIntegerField(unique=True, verbose_name='Número de edición')),
                ('titulo_edicion', models.CharField(max_length=200, verbose_name='Título de la edición')),
                ('contenido', models.CharField(blank=True, max_length=5000, verbose_name='Descripción corta')),
                ('imagen', models.ImageField(upload_to='ediciones/', verbose_name='Imagen')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('url_impresa', models.URLField(blank=True, null=True, verbose_name='Versión impresa (URL)')),
            ],
            options={
                'verbose_name': 'Edición',
                'verbose_name_plural': 'Ediciones',
                'ordering': ['-fecha_publicacion', '-numero_edicion'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.EmailField(max_length=200, verbose_name='correo electrónico')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de envío')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
