# Generated by Django 5.2.6 on 2025-10-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ediciones',
            name='imagen',
            field=models.ImageField(upload_to='RMM/Ediciones/', verbose_name='Imagen'),
        ),
    ]
