# Generated by Django 5.2.6 on 2025-10-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_alter_ediciones_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='fecha_publicacion',
        ),
    ]
