# Generated by Django 5.2.6 on 2025-09-20 08:57

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido del comentario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LikeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Like de Blog',
                'verbose_name_plural': 'Likes de Blogs',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_blog', models.CharField(max_length=200, verbose_name='Título del blog')),
                ('contenido', ckeditor.fields.RichTextField(blank=True, verbose_name='Contenido')),
                ('imagen_principal', models.ImageField(upload_to='blogs/', verbose_name='Imagen')),
                ('banner', models.ImageField(upload_to='banners/', verbose_name='Banner')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('articulos', models.ManyToManyField(blank=True, related_name='blogs', to='articles.articulos')),
                ('categoria_blog', models.ForeignKey(help_text='Selecciona la categoría a la que pertenece este blog', on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.categoria_blog', verbose_name='Categoría del blog')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
