# Generated by Django 5.2.6 on 2025-10-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_categoria_blog_delete_categoria_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.TextField(blank=True, null=True, verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen_principal',
            field=models.TextField(blank=True, null=True, verbose_name='Imagen'),
        ),
    ]
