# Generated by Django 5.2.6 on 2025-10-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_banner_alter_blog_imagen_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.CharField(blank=True, null=True, verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen_principal',
            field=models.CharField(blank=True, null=True, verbose_name='Imagen'),
        ),
    ]
