# Generated by Django 5.2.6 on 2025-10-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_banner_alter_blog_imagen_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='RMM/Noticias-Banner/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='RMM/Noticias-ImagenPrincipal/', verbose_name='Imagen'),
        ),
    ]
