# Generated by Django 5.2.6 on 2025-09-22 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        ('blog', '0003_alter_blog_banner_alter_blog_categoria_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='categoria_articulo',
            field=models.ForeignKey(blank=True, help_text='Selecciona la categoría a la que pertenece este artículo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='blog.categoria_blog', verbose_name='Categoría del artículo'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/', verbose_name='Imagen'),
        ),
    ]
