# Generated by Django 5.2.6 on 2025-09-23 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articulos_categoria_articulo_alter_articulos_banner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioarticulo',
            name='nivel',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='comentarioarticulo',
            index=models.Index(fields=['articulo', 'parent'], name='articles_co_articul_56094e_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarioarticulo',
            index=models.Index(fields=['articulo', 'nivel'], name='articles_co_articul_5040bd_idx'),
        ),
    ]
