# Generated by Django 5.2.7 on 2025-10-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_articulos_categoria_articulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='categoria_articulo',
        ),
    ]
