# Generated by Django 5.2.6 on 2025-09-20 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoría de Foro',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000, null=True, verbose_name='Título del tema')),
                ('contenido', models.TextField(blank=True, null=True, unique=True, verbose_name='Contenido del tema')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_foro', to=settings.AUTH_USER_MODEL)),
                ('categoria_foro', models.ForeignKey(help_text='Selecciona la categoría a la que pertenece este tema', on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='foro.categoria_foro', verbose_name='Categoría del foro')),
            ],
            options={
                'verbose_name': 'Tema de Foro',
                'verbose_name_plural': 'Temas de Foro',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido del comentario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_foro', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='foro.comentariotema')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='foro.tema')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LikeTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_temas', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='foro.tema')),
            ],
            options={
                'verbose_name': 'Like de Tema',
                'verbose_name_plural': 'Likes de Temas',
                'unique_together': {('tema', 'usuario')},
            },
        ),
    ]
