# Generated by Django 5.2.6 on 2025-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoría de Foro',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido del comentario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LikeTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Like de Tema',
                'verbose_name_plural': 'Likes de Temas',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del tema')),
                ('contenido', models.TextField(verbose_name='Contenido del tema')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tema de Foro',
                'verbose_name_plural': 'Temas de Foro',
                'ordering': ['-creado_en'],
            },
        ),
    ]
