# Generated by Django 5.2.6 on 2025-09-21 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComentarioTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='foro.comentariotema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_comentarios_foro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like de Comentario de Foro',
                'verbose_name_plural': 'Likes de Comentarios de Foro',
                'unique_together': {('comentario', 'usuario')},
            },
        ),
    ]
