# Generated by Django 5.2.6 on 2025-09-20 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariotema',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_foro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentariotema',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='foro.comentariotema'),
        ),
        migrations.AddField(
            model_name='liketema',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_temas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tema',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_foro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liketema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='foro.tema'),
        ),
        migrations.AddField(
            model_name='comentariotema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='foro.tema'),
        ),
        migrations.AlterUniqueTogether(
            name='liketema',
            unique_together={('tema', 'usuario')},
        ),
    ]
