# Generated by Django 5.2.6 on 2025-09-23 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_likecomentariotema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariotema',
            name='nivel',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='comentariotema',
            index=models.Index(fields=['tema', 'parent'], name='foro_coment_tema_id_688c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='comentariotema',
            index=models.Index(fields=['tema', 'nivel'], name='foro_coment_tema_id_852d59_idx'),
        ),
    ]
