# Generated by Django 5.2.6 on 2025-09-20 08:57

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_articulo', models.CharField(max_length=200, verbose_name='Título del artículo')),
                ('contenido', ckeditor.fields.RichTextField(blank=True, verbose_name='Contenido')),
                ('imagen_principal', models.ImageField(upload_to='articulos/', verbose_name='Imagen')),
                ('banner', models.ImageField(upload_to='banners/', verbose_name='Banner')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='LikeArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Like de Artículo',
                'verbose_name_plural': 'Likes de Artículos',
            },
        ),
        migrations.CreateModel(
            name='ComentarioArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido del comentario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='articles.articulos')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
