# Generated by Django 5.2.6 on 2025-10-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comentarioarticulo_nivel_and_more'),
        ('blog', '0005_alter_blog_options_alter_blog_categoria_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='categoria_articulo',
            field=models.ForeignKey(blank=True, help_text='Selecciona la categoría a la que pertenece este artículo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='blog.categoria_blog', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
