# Generated by Django 5.2.6 on 2025-10-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_articulos_categoria_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='RMM/Articulos-Banner/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='RMM/Articulos-ImagenPrincipal/', verbose_name='Imagen'),
        ),
    ]
